// Code generated by Kitex v0.9.1. DO NOT EDIT.

package cartservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	cart "github.com/czczcz831/tiktok-mall/client/cart/kitex_gen/cart"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"AddProductToCart": kitex.NewMethodInfo(
		addProductToCartHandler,
		newCartServiceAddProductToCartArgs,
		newCartServiceAddProductToCartResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ClearCart": kitex.NewMethodInfo(
		clearCartHandler,
		newCartServiceClearCartArgs,
		newCartServiceClearCartResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetCart": kitex.NewMethodInfo(
		getCartHandler,
		newCartServiceGetCartArgs,
		newCartServiceGetCartResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	cartServiceServiceInfo                = NewServiceInfo()
	cartServiceServiceInfoForClient       = NewServiceInfoForClient()
	cartServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return cartServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return cartServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return cartServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "CartService"
	handlerType := (*cart.CartService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "cart",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func addProductToCartHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*cart.CartServiceAddProductToCartArgs)
	realResult := result.(*cart.CartServiceAddProductToCartResult)
	success, err := handler.(cart.CartService).AddProductToCart(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCartServiceAddProductToCartArgs() interface{} {
	return cart.NewCartServiceAddProductToCartArgs()
}

func newCartServiceAddProductToCartResult() interface{} {
	return cart.NewCartServiceAddProductToCartResult()
}

func clearCartHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*cart.CartServiceClearCartArgs)
	realResult := result.(*cart.CartServiceClearCartResult)
	success, err := handler.(cart.CartService).ClearCart(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCartServiceClearCartArgs() interface{} {
	return cart.NewCartServiceClearCartArgs()
}

func newCartServiceClearCartResult() interface{} {
	return cart.NewCartServiceClearCartResult()
}

func getCartHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*cart.CartServiceGetCartArgs)
	realResult := result.(*cart.CartServiceGetCartResult)
	success, err := handler.(cart.CartService).GetCart(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCartServiceGetCartArgs() interface{} {
	return cart.NewCartServiceGetCartArgs()
}

func newCartServiceGetCartResult() interface{} {
	return cart.NewCartServiceGetCartResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) AddProductToCart(ctx context.Context, req *cart.AddProductToCartReq) (r *cart.AddProductToCartResp, err error) {
	var _args cart.CartServiceAddProductToCartArgs
	_args.Req = req
	var _result cart.CartServiceAddProductToCartResult
	if err = p.c.Call(ctx, "AddProductToCart", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ClearCart(ctx context.Context, req *cart.ClearCartReq) (r *cart.ClearCartResp, err error) {
	var _args cart.CartServiceClearCartArgs
	_args.Req = req
	var _result cart.CartServiceClearCartResult
	if err = p.c.Call(ctx, "ClearCart", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetCart(ctx context.Context, req *cart.GetCartReq) (r *cart.GetCartResp, err error) {
	var _args cart.CartServiceGetCartArgs
	_args.Req = req
	var _result cart.CartServiceGetCartResult
	if err = p.c.Call(ctx, "GetCart", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
