// Code generated by hertz generator.

package api

import (
	"context"

	"fmt"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/czczcz831/tiktok-mall/app/api/biz/dal/casbin"
	"github.com/czczcz831/tiktok-mall/app/api/biz/dal/redis"
	"github.com/czczcz831/tiktok-mall/app/api/conf"
	"github.com/czczcz831/tiktok-mall/common/utils"
)

func RootMiddleware() app.HandlerFunc {
	return func(ctx context.Context, c *app.RequestContext) {
		token := c.GetRequest().Header.Get("Authorization")
		if token == "" {
			c.AbortWithMsg("token is empty", consts.StatusUnauthorized)
			return
		}

		publicKeyHexString := conf.GetConf().JWT.PublicSecret

		//Verify token in redis
		redisKey := fmt.Sprintf("token:%s", token)
		exists, err := redis.RedisClient.Exists(context.Background(), redisKey).Result()
		if err != nil {
			c.AbortWithStatus(consts.StatusInternalServerError)
			return
		}

		if exists == 0 {
			c.AbortWithMsg("Not login", consts.StatusUnauthorized)
			return
		}

		//这一步其实没必要了，uuid可以存redis里，但还是双重验证一下吧
		//这一步其实没必要了，uuid可以存redis里，但还是双重验证一下吧
		uuid, _, err := utils.VerifyToken(token, publicKeyHexString)
		if err != nil {
			c.AbortWithMsg("Invalid token", consts.StatusUnauthorized)
			return
		}

		//Blacklist
		banned, err := casbin.CasbinEnforcer.HasRoleForUser(uuid, casbin.BANNED_ROLE)
		if err != nil {
			c.AbortWithStatus(consts.StatusInternalServerError)
			return
		}
		if banned {
			c.AbortWithMsg("Banned", consts.StatusUnauthorized)
			return
		}

		// 设置uuid和token到上下文
		c.Set("uuid", uuid)
		c.Set("token", token)
	}
}

func rootMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{RootMiddleware()}
}

// 更新商品需要角色拥有SELLER_OBJECT权限

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _refreshtokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

// 更新商品需要角色拥有SELLER_OBJECT权限
func _updateproductMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		casbin.CasbinHertzMiddleware.RequiresPermissions(casbin.SELLER_OBJECT),
	}
}

func _getproductlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _productMw() []app.HandlerFunc {
	// your code...
	return nil
}

// 创建商品需要角色拥有SELLER_OBJECT权限
func _createproductMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		casbin.CasbinHertzMiddleware.RequiresPermissions(casbin.SELLER_OBJECT),
	}
}

// 删除商品需要角色拥有SELLER_OBJECT权限
func _deleteproductMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		casbin.CasbinHertzMiddleware.RequiresPermissions(casbin.SELLER_OBJECT),
	}
}

func _getproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

// 购物车组需要角色拥有CUSTOMER_OBJECT权限
func _cartMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		casbin.CasbinHertzMiddleware.RequiresPermissions(casbin.CUSTOMER_OBJECT),
	}
}

func _clearcartMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		casbin.CasbinHertzMiddleware.RequiresPermissions(casbin.CUSTOMER_OBJECT),
	}
}

func _getcartMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		casbin.CasbinHertzMiddleware.RequiresPermissions(casbin.CUSTOMER_OBJECT),
	}
}

func _addproducttocartMw() []app.HandlerFunc {
	// your code...
	return nil
}

// 结算需要角色拥有CUSTOMER_OBJECT权限
func _checkoutMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		casbin.CasbinHertzMiddleware.RequiresPermissions(casbin.CUSTOMER_OBJECT),
	}
}

// 结算组需要角色拥有CUSTOMER_OBJECT权限
func _checkout0Mw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		casbin.CasbinHertzMiddleware.RequiresPermissions(casbin.CUSTOMER_OBJECT),
	}
}

func _chargeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checkout1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateaddressMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _credit_cardMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createcreditcardMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcreditcardMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletecreditcardMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatecreditcardMw() []app.HandlerFunc {
	// your code...
	return nil
}

// 地址组需要角色拥有CUSTOMER_OBJECT权限
func _addressMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		casbin.CasbinHertzMiddleware.RequiresPermissions(casbin.CUSTOMER_OBJECT),
	}
}

func _createaddressMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getaddressMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteaddressMw() []app.HandlerFunc {
	// your code...
	return nil
}

// 支付需要角色拥有CUSTOMER_OBJECT权限
func _paymentMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		casbin.CasbinHertzMiddleware.RequiresPermissions(casbin.CUSTOMER_OBJECT),
	}
}

// 登出需要角色拥有CUSTOMER_OBJECT权限
func _logoutMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		casbin.CasbinHertzMiddleware.RequiresPermissions(casbin.CUSTOMER_OBJECT),
	}
}

// 获取用户订单需要角色拥有CUSTOMER_OBJECT权限
func _getuserordersMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		casbin.CasbinHertzMiddleware.RequiresPermissions(casbin.CUSTOMER_OBJECT),
	}
}

// 获取用户信息需要角色拥有CUSTOMER_OBJECT权限
func _getuserinfoMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		casbin.CasbinHertzMiddleware.RequiresPermissions(casbin.CUSTOMER_OBJECT),
	}
}

func _einoMw() []app.HandlerFunc {
	// 需要登录
	return []app.HandlerFunc{
		casbin.CasbinHertzMiddleware.RequiresPermissions(casbin.CUSTOMER_OBJECT),
	}
}

func _callassistantagentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _orderMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		casbin.CasbinHertzMiddleware.RequiresPermissions(casbin.CUSTOMER_OBJECT),
	}
}

func _updateorderaddressMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _cancelchargeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adduserblacklistMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		casbin.CasbinHertzMiddleware.RequiresRoles(casbin.ADMIN_ROLE),
	}
}

func _user0Mw() []app.HandlerFunc {
	// your code...
	return nil
}
