// Code generated by thriftgo (0.3.7). DO NOT EDIT.

package eino

import (
	"context"
	"fmt"
	"github.com/apache/thrift/lib/go/thrift"
	"strings"
)

type CallAssistantAgentReq struct {
	UserUuid string `thrift:"user_uuid,1" frugal:"1,default,string" json:"user_uuid"`
	Content  string `thrift:"content,2" frugal:"2,default,string" json:"content"`
}

func NewCallAssistantAgentReq() *CallAssistantAgentReq {
	return &CallAssistantAgentReq{}
}

func (p *CallAssistantAgentReq) InitDefault() {
	*p = CallAssistantAgentReq{}
}

func (p *CallAssistantAgentReq) GetUserUuid() (v string) {
	return p.UserUuid
}

func (p *CallAssistantAgentReq) GetContent() (v string) {
	return p.Content
}
func (p *CallAssistantAgentReq) SetUserUuid(val string) {
	p.UserUuid = val
}
func (p *CallAssistantAgentReq) SetContent(val string) {
	p.Content = val
}

var fieldIDToName_CallAssistantAgentReq = map[int16]string{
	1: "user_uuid",
	2: "content",
}

func (p *CallAssistantAgentReq) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_CallAssistantAgentReq[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *CallAssistantAgentReq) ReadField1(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.UserUuid = v
	}
	return nil
}
func (p *CallAssistantAgentReq) ReadField2(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.Content = v
	}
	return nil
}

func (p *CallAssistantAgentReq) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("CallAssistantAgentReq"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *CallAssistantAgentReq) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("user_uuid", thrift.STRING, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.UserUuid); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *CallAssistantAgentReq) writeField2(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("content", thrift.STRING, 2); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.Content); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}

func (p *CallAssistantAgentReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CallAssistantAgentReq(%+v)", *p)

}

func (p *CallAssistantAgentReq) DeepEqual(ano *CallAssistantAgentReq) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.UserUuid) {
		return false
	}
	if !p.Field2DeepEqual(ano.Content) {
		return false
	}
	return true
}

func (p *CallAssistantAgentReq) Field1DeepEqual(src string) bool {

	if strings.Compare(p.UserUuid, src) != 0 {
		return false
	}
	return true
}
func (p *CallAssistantAgentReq) Field2DeepEqual(src string) bool {

	if strings.Compare(p.Content, src) != 0 {
		return false
	}
	return true
}

type CallAssistantAgentResp struct {
	Reply string `thrift:"reply,1" frugal:"1,default,string" json:"reply"`
}

func NewCallAssistantAgentResp() *CallAssistantAgentResp {
	return &CallAssistantAgentResp{}
}

func (p *CallAssistantAgentResp) InitDefault() {
	*p = CallAssistantAgentResp{}
}

func (p *CallAssistantAgentResp) GetReply() (v string) {
	return p.Reply
}
func (p *CallAssistantAgentResp) SetReply(val string) {
	p.Reply = val
}

var fieldIDToName_CallAssistantAgentResp = map[int16]string{
	1: "reply",
}

func (p *CallAssistantAgentResp) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_CallAssistantAgentResp[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *CallAssistantAgentResp) ReadField1(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.Reply = v
	}
	return nil
}

func (p *CallAssistantAgentResp) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("CallAssistantAgentResp"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *CallAssistantAgentResp) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("reply", thrift.STRING, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.Reply); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *CallAssistantAgentResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CallAssistantAgentResp(%+v)", *p)

}

func (p *CallAssistantAgentResp) DeepEqual(ano *CallAssistantAgentResp) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Reply) {
		return false
	}
	return true
}

func (p *CallAssistantAgentResp) Field1DeepEqual(src string) bool {

	if strings.Compare(p.Reply, src) != 0 {
		return false
	}
	return true
}

type EinoService interface {
	CallAssistantAgent(ctx context.Context, req *CallAssistantAgentReq) (r *CallAssistantAgentResp, err error)
}

type EinoServiceClient struct {
	c thrift.TClient
}

func NewEinoServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *EinoServiceClient {
	return &EinoServiceClient{
		c: thrift.NewTStandardClient(f.GetProtocol(t), f.GetProtocol(t)),
	}
}

func NewEinoServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *EinoServiceClient {
	return &EinoServiceClient{
		c: thrift.NewTStandardClient(iprot, oprot),
	}
}

func NewEinoServiceClient(c thrift.TClient) *EinoServiceClient {
	return &EinoServiceClient{
		c: c,
	}
}

func (p *EinoServiceClient) Client_() thrift.TClient {
	return p.c
}

func (p *EinoServiceClient) CallAssistantAgent(ctx context.Context, req *CallAssistantAgentReq) (r *CallAssistantAgentResp, err error) {
	var _args EinoServiceCallAssistantAgentArgs
	_args.Req = req
	var _result EinoServiceCallAssistantAgentResult
	if err = p.Client_().Call(ctx, "CallAssistantAgent", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

type EinoServiceProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
	handler      EinoService
}

func (p *EinoServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
	p.processorMap[key] = processor
}

func (p *EinoServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
	processor, ok = p.processorMap[key]
	return processor, ok
}

func (p *EinoServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
	return p.processorMap
}

func NewEinoServiceProcessor(handler EinoService) *EinoServiceProcessor {
	self := &EinoServiceProcessor{handler: handler, processorMap: make(map[string]thrift.TProcessorFunction)}
	self.AddToProcessorMap("CallAssistantAgent", &einoServiceProcessorCallAssistantAgent{handler: handler})
	return self
}
func (p *EinoServiceProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	name, _, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return false, err
	}
	if processor, ok := p.GetProcessorFunction(name); ok {
		return processor.Process(ctx, seqId, iprot, oprot)
	}
	iprot.Skip(thrift.STRUCT)
	iprot.ReadMessageEnd()
	x := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function "+name)
	oprot.WriteMessageBegin(name, thrift.EXCEPTION, seqId)
	x.Write(oprot)
	oprot.WriteMessageEnd()
	oprot.Flush(ctx)
	return false, x
}

type einoServiceProcessorCallAssistantAgent struct {
	handler EinoService
}

func (p *einoServiceProcessorCallAssistantAgent) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := EinoServiceCallAssistantAgentArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("CallAssistantAgent", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return false, err
	}

	iprot.ReadMessageEnd()
	var err2 error
	result := EinoServiceCallAssistantAgentResult{}
	var retval *CallAssistantAgentResp
	if retval, err2 = p.handler.CallAssistantAgent(ctx, args.Req); err2 != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing CallAssistantAgent: "+err2.Error())
		oprot.WriteMessageBegin("CallAssistantAgent", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return true, err2
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("CallAssistantAgent", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(ctx); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

type EinoServiceCallAssistantAgentArgs struct {
	Req *CallAssistantAgentReq `thrift:"req,1" frugal:"1,default,CallAssistantAgentReq" json:"req"`
}

func NewEinoServiceCallAssistantAgentArgs() *EinoServiceCallAssistantAgentArgs {
	return &EinoServiceCallAssistantAgentArgs{}
}

func (p *EinoServiceCallAssistantAgentArgs) InitDefault() {
	*p = EinoServiceCallAssistantAgentArgs{}
}

var EinoServiceCallAssistantAgentArgs_Req_DEFAULT *CallAssistantAgentReq

func (p *EinoServiceCallAssistantAgentArgs) GetReq() (v *CallAssistantAgentReq) {
	if !p.IsSetReq() {
		return EinoServiceCallAssistantAgentArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *EinoServiceCallAssistantAgentArgs) SetReq(val *CallAssistantAgentReq) {
	p.Req = val
}

var fieldIDToName_EinoServiceCallAssistantAgentArgs = map[int16]string{
	1: "req",
}

func (p *EinoServiceCallAssistantAgentArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *EinoServiceCallAssistantAgentArgs) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_EinoServiceCallAssistantAgentArgs[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *EinoServiceCallAssistantAgentArgs) ReadField1(iprot thrift.TProtocol) error {
	p.Req = NewCallAssistantAgentReq()
	if err := p.Req.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *EinoServiceCallAssistantAgentArgs) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("CallAssistantAgent_args"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *EinoServiceCallAssistantAgentArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("req", thrift.STRUCT, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.Req.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *EinoServiceCallAssistantAgentArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EinoServiceCallAssistantAgentArgs(%+v)", *p)

}

func (p *EinoServiceCallAssistantAgentArgs) DeepEqual(ano *EinoServiceCallAssistantAgentArgs) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Req) {
		return false
	}
	return true
}

func (p *EinoServiceCallAssistantAgentArgs) Field1DeepEqual(src *CallAssistantAgentReq) bool {

	if !p.Req.DeepEqual(src) {
		return false
	}
	return true
}

type EinoServiceCallAssistantAgentResult struct {
	Success *CallAssistantAgentResp `thrift:"success,0,optional" frugal:"0,optional,CallAssistantAgentResp" json:"success,omitempty"`
}

func NewEinoServiceCallAssistantAgentResult() *EinoServiceCallAssistantAgentResult {
	return &EinoServiceCallAssistantAgentResult{}
}

func (p *EinoServiceCallAssistantAgentResult) InitDefault() {
	*p = EinoServiceCallAssistantAgentResult{}
}

var EinoServiceCallAssistantAgentResult_Success_DEFAULT *CallAssistantAgentResp

func (p *EinoServiceCallAssistantAgentResult) GetSuccess() (v *CallAssistantAgentResp) {
	if !p.IsSetSuccess() {
		return EinoServiceCallAssistantAgentResult_Success_DEFAULT
	}
	return p.Success
}
func (p *EinoServiceCallAssistantAgentResult) SetSuccess(x interface{}) {
	p.Success = x.(*CallAssistantAgentResp)
}

var fieldIDToName_EinoServiceCallAssistantAgentResult = map[int16]string{
	0: "success",
}

func (p *EinoServiceCallAssistantAgentResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *EinoServiceCallAssistantAgentResult) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 0:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField0(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_EinoServiceCallAssistantAgentResult[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *EinoServiceCallAssistantAgentResult) ReadField0(iprot thrift.TProtocol) error {
	p.Success = NewCallAssistantAgentResp()
	if err := p.Success.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *EinoServiceCallAssistantAgentResult) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("CallAssistantAgent_result"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField0(oprot); err != nil {
			fieldId = 0
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *EinoServiceCallAssistantAgentResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err = oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
			goto WriteFieldBeginError
		}
		if err := p.Success.Write(oprot); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 end error: ", p), err)
}

func (p *EinoServiceCallAssistantAgentResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EinoServiceCallAssistantAgentResult(%+v)", *p)

}

func (p *EinoServiceCallAssistantAgentResult) DeepEqual(ano *EinoServiceCallAssistantAgentResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field0DeepEqual(ano.Success) {
		return false
	}
	return true
}

func (p *EinoServiceCallAssistantAgentResult) Field0DeepEqual(src *CallAssistantAgentResp) bool {

	if !p.Success.DeepEqual(src) {
		return false
	}
	return true
}
