name: Docker Build and Push All Images

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build-and-push-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALI_REGISTRY }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Build and Push All Services
        run: |
          # Define all services and their Dockerfile paths
          declare -A SERVICES=(
            ["api"]="docker/Dockerfile.api"
            ["auth"]="docker/Dockerfile.auth"
            ["cart"]="docker/Dockerfile.cart"
            ["checkout"]="docker/Dockerfile.checkout"
            ["eino"]="docker/Dockerfile.eino"
            ["order"]="docker/Dockerfile.order"
            ["payment"]="docker/Dockerfile.payment"
            ["product"]="docker/Dockerfile.product"
            ["user"]="docker/Dockerfile.user"
          )

          # Loop through each service and build/push its image
          for SERVICE in "${!SERVICES[@]}"; do
            IMAGE_NAME="${{ secrets.ALI_REGISTRY }}/czczcz/tiktok-mall-${SERVICE}"
            DOCKERFILE="${SERVICES[$SERVICE]}"
            
            echo "Building and pushing ${SERVICE} service..."
            docker buildx build \
              --file "${DOCKERFILE}" \
              --tag "${IMAGE_NAME}:latest" \
              --tag "${IMAGE_NAME}:${{ github.sha }}" \
              --push \
              .
            
            if [ $? -eq 0 ]; then
              echo "Successfully built and pushed ${SERVICE} service"
            else
              echo "Failed to build and push ${SERVICE} service"
              exit 1
            fi
          done
          
          echo "All services
